apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: pdb-zone-a
  labels:
    app.kubernetes.io/name: webapp
    app.kubernetes.io/part-of: webapp
    app.kubernetes.io/component: zone-pdb
    app.kubernetes.io/instance: zone-a
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: webapp
      zone: zone-a
