apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: webapp-cert
  labels:
    app.kubernetes.io/name: webapp
    app.kubernetes.io/part-of: webapp
    app.kubernetes.io/component: cert-request
spec:
  secretName: webapp-cert-secret
  issuerRef:
    name: http01-issuer
    kind: ClusterIssuer
  commonName: webapp.com
  dnsNames:
  - webapp.com
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - webapp.com
  secretTemplate:
    labels:
      app.kubernetes.io/name: webapp
      app.kubernetes.io/part-of: webapp
      app.kubernetes.io/component: webapp-cert-secret
