apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: http01-issuer
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: admin@webapp.com
    privateKeySecretRef:
      name: letsencrypt-issuer-account-key
    solvers:
    - http01:
        ingress:
          ingressClassName: nginx
